config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new,    :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', :via => :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
      <ul class="list-unstyled">
        <% object.errors.full_messages.each do |msg| %>
            <li><span class="glyphicon glyphicon-remove-sign"></span><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <div class="list-group">
      <%= render partial: 'shared/feed_item', collection: @feed_items %>
    </div>
    <%= will_paginate @feed_items, class: 'center' %>
<% end %>

app/views/shared/_feed_item.html.erb
<article class="list-group-item" id="<%= feed_item.id %>">
  <aside class="col-md-1">
    <%= link_to gravatar_for(feed_item.user, size: 52), feed_item.user, class: 'pull-left' %>
  </aside>
  <section class="col-md-offset-1">
    <h4 class="list-group-item-heading">
      <%= link_to feed_item.user.name, feed_item.user %>
    </h4>
    <p class="list-group-item-text">
      <%= wrap(feed_item.content) %>
    </p>
    <span class="list-group-item-text">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
      <% if current_user?(feed_item.user) || is_admin?(current_user) %>
          <%= link_to 'delete', feed_item, method: :delete,
                      data: { confirm: 'Are you sure?' },
                      title: 'Delete this micropost',
                      class: 'label label-danger' %>
      <% end %>
    </span>
  </section>
</article>

app/views/shared/_followers.html.erb
<% followers = get_followers(@user) %>
<% if followers.any? %>
    <% followers.each do |follower| %>
        <%= link_to gravatar_for(follower, size: 30), follower %>
    <% end %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <%= f.text_area :content, class: 'form-control micropost', rows: 7, placeholder: "Compose new micropost..." %>
    </div>

    <%= f.submit 'Post', class: 'btn btn-lg btn-primary' %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<% @user ||= current_user %>
<% if current_page?(@user) %>
    <%= gravatar_for(@user, size: 52) %>
    <h1>
      <%= @user.name %>
    </h1>
<% else %>
    <%= link_to gravatar_for(@user, size: 52), user_path(@user) %>
    <h1>
      <%= link_to @user.name, @user %>
    </h1>
<% end %>
<span>
  <%= pluralize(@user.microposts.count, "micropost") %>
</span>