config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new,    :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', :via => :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <span id="rails_logo"><%= link_to image_tag("rails.png", alt: "Rails", title: "Built on Rails"), 'http://rubyonrails.org/' %></span>
    <p class="text-muted">
      <a href="http://railstutorial.org/">Rails Tutorial</a> by Michael Hartl<br><br>
      <%= link_to "About",   about_path %></li> /
      <%= link_to "Contact", contact_path %></li> /
      <a href="http://news.railstutorial.org/">News</a>
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Sample App", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>

        <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle js-activated" data-hover="dropdown"><%= gravatar_for(current_user, size: 20) %><%= current_user.name %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Your profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div id="wrap">
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render :partial => 'layouts/flash', :locals => {:flash => flash} if yield(:display_flash) != 'no' %>
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>